### ISSUE TITLE
Quest "The Fel and the Furious" is not completable within time limit

### ISSUE THREAD

**Issue by Delinquence** [Nextcalibur/Bugtracker#568] opened 2020-07-17 15:42 UTC
In this quest you're supposed to control a fel reaver, but half of it's abilities are not working, so you can only use 2 spells that have too long of a cooldown to kill the 60 infernals. Besides that the infernals are non targetable, so you cannot use the fel reavers basic attack to kill them.

**Comment by MihawkEntropius** [comment] 2020-07-17 16:12
https://github.com/Nextcalibur/Bugtracker/issues/17

**Comment by Nextcalibur** [comment] 2020-07-18 12:15
Duplicate of #17

**Closed by Nextcalibur** 2020-07-18 12:15 UTC
Labels: duplicate
